package main

import (
	"bufio"
	"encoding/json"
	"fmt"
	"io"
	"math"
	"os"
	"runtime"
	"strconv"
	"strings"
	"sync"
	"sync/atomic"
	"time"

	"chess/board"
	"chess/engine"
	"chess/game"
	"chess/moves"
)

// Importing the Lichess evaluation database.
//
// The reason this exists is a measurement: positions generated by depth-2
// self-play after ten random opening plies are not the positions this
// engine meets. Squared error against a depth-6 reference was 1.57 on the
// training distribution and 2.80 on the playing one, and the material
// profile differed as sharply (mean gap 3.47 against 6.79, 22% lopsided
// against 53%). The network had been fitted to a population it does not
// play in.
//
// The Lichess dump fixes three things at once that no amount of self-play
// tuning could: the positions come from real games, the labels come from
// a search at depth 46 to 58 rather than depth 3, and there are about 214
// million of them against the 2.7 million self-play has accumulated.

// evalLine is one record of the dump. Only the fields used are declared;
// the file also carries principal variations, which are not needed here.
type evalLine struct {
	FEN   string `json:"fen"`
	Evals []struct {
		PVs []struct {
			CP   *int   `json:"cp"`
			Mate *int   `json:"mate"`
			Line string `json:"line"`
		} `json:"pvs"`
		Depth int `json:"depth"`
	} `json:"evals"`
}

// bestEval picks the deepest analysis on the record and returns its score
// in pawns from White's point of view, which is how the dump stores it.
// Mates are rejected: a forced mate
// saturates any target and teaches a static function nothing, which is
// the same reason the self-play path skips them.
func (e evalLine) bestEval() (float64, bool) {
	bestDepth, best := -1, 0
	for _, ev := range e.Evals {
		if ev.Depth <= bestDepth || len(ev.PVs) == 0 {
			continue
		}
		if ev.PVs[0].CP == nil {
			continue // a mate line, or a record with no score
		}
		bestDepth, best = ev.Depth, *ev.PVs[0].CP
	}
	if bestDepth < 0 {
		return 0, false
	}
	return float64(best) / 100, true
}

// The dump stores four-field FENs. The parser wants six, and loosening it
// is the wrong fix: it is also what validates positions coming from the
// browser. Pad instead.
func padFEN(f string) string {
	if n := len(strings.Fields(f)); n == 4 {
		return f + " 0 1"
	}
	return f
}

// ExtractOpenings writes FENs of early-game positions from the dump to a
// plain text file, one per line, for use as an opening book.
//
// The purpose is idea 2 of the plateau campaign: self-play currently
// starts from ten uniformly random plies, which produces positions no
// real game reaches. A book drawn from analysed human games starts each
// self-play game somewhere plausible instead.
//
// "Early game" is defined by material still on the board rather than by a
// move number, because the dump does not record move numbers.
func ExtractOpenings(r io.Reader, path string, max, minPieces int) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	w := bufio.NewWriterSize(f, 1<<20)
	defer w.Flush()

	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 1<<20), 1<<22)
	seen := map[string]bool{}
	written, read := 0, 0
	t0 := time.Now()
	for sc.Scan() && (max <= 0 || written < max) {
		read++
		var rec evalLine
		if err := json.Unmarshal(sc.Bytes(), &rec); err != nil {
			continue
		}
		placement := rec.FEN
		if i := strings.IndexByte(placement, ' '); i > 0 {
			placement = placement[:i]
		}
		pieces := 0
		for i := 0; i < len(placement); i++ {
			if c := placement[i]; (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') {
				pieces++
			}
		}
		// Above 32 is a variant; below minPieces the game is past its
		// opening and is not what a book is for.
		if pieces > 32 || pieces < minPieces {
			continue
		}
		if seen[rec.FEN] {
			continue
		}
		// Parsed before being written, so the book cannot contain a
		// position that will fail at the point it is used.
		if _, err := game.ParseFEN(padFEN(rec.FEN)); err != nil {
			continue
		}
		seen[rec.FEN] = true
		if _, err := w.WriteString(padFEN(rec.FEN) + "\n"); err != nil {
			return err
		}
		written++
		if written%20000 == 0 {
			fmt.Printf("  %d openings from %d records, %s\n",
				written, read, time.Since(t0).Truncate(time.Second))
		}
	}
	fmt.Printf("wrote %d opening positions to %s (from %d records, %s)\n",
		written, path, read, time.Since(t0).Truncate(time.Second))
	return nil
}

// bestPV returns the whole principal variation from the deepest analysis,
// as a list of UCI moves.
//
// Taking only the first move produces a book one ply deep. Measured, such
// a book covered a single ply from the initial position and 2.4 plies on
// average from a real opening, and was worth +2 +/- 28 Elo, which is
// nothing. The records carry ten-move variations, and replaying them
// gives a book that stays in book for a real opening's length.
func (e evalLine) bestPV() ([]string, bool) {
	bestDepth := -1
	var best []string
	for _, ev := range e.Evals {
		if ev.Depth <= bestDepth || len(ev.PVs) == 0 {
			continue
		}
		fields := strings.Fields(ev.PVs[0].Line)
		if len(fields) == 0 {
			continue
		}
		bestDepth, best = ev.Depth, fields
	}
	return best, bestDepth >= 0
}

// bestLine returns the first move of the principal variation from the
// deepest analysis on the record. Mate lines are kept here, unlike in
// training: a move that forces mate is exactly the move to play, even
// though the score it carries teaches a static evaluation nothing.
func (e evalLine) bestLine() (string, bool) {
	bestDepth, best := -1, ""
	for _, ev := range e.Evals {
		if ev.Depth <= bestDepth || len(ev.PVs) == 0 {
			continue
		}
		line := strings.TrimSpace(ev.PVs[0].Line)
		if line == "" {
			continue
		}
		first := line
		if i := strings.IndexByte(line, ' '); i > 0 {
			first = line[:i]
		}
		if len(first) < 4 {
			continue
		}
		bestDepth, best = ev.Depth, first
	}
	return best, bestDepth >= 0
}

// ExtractBook writes an opening book of "FEN|move" lines for play, taking
// the move from the deepest principal variation on each record.
//
// This is a different artefact from ExtractOpenings, which writes bare
// positions to start self-play from. Here the move is the point: the
// engine plays it instead of searching, which buys forty plies of depth
// in the opening for the cost of a map lookup.
// WARNING: this reads the Lichess *evaluation* database (fen, evals with
// cp/mate/depth, and principal variations) and takes its moves from the
// deepest engine line via bestPV. Those are externally computed position
// scores, which this project does not allow: a game database is fine, a
// database of engine evaluations is not, and a book built from one is
// another engine's opinion wearing this one's name.
//
// Do not run this to build a book the engine plays. A book from real game
// results (the most played move per position, from the PGN database) is
// allowed and would need a different reader; this is not it.
func ExtractBook(r io.Reader, path string, max, minPieces int) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	w := bufio.NewWriterSize(f, 1<<20)
	defer w.Flush()

	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 1<<20), 1<<22)
	seen := map[string]bool{}
	written, read, illegal := 0, 0, 0
	t0 := time.Now()
	for sc.Scan() && (max <= 0 || written < max) {
		read++
		var rec evalLine
		if err := json.Unmarshal(sc.Bytes(), &rec); err != nil {
			continue
		}
		placement := rec.FEN
		if i := strings.IndexByte(placement, ' '); i > 0 {
			placement = placement[:i]
		}
		pieces := 0
		for i := 0; i < len(placement); i++ {
			if c := placement[i]; (c >= 'a' && c <= 'z') || (c >= 'A' && c <= 'Z') {
				pieces++
			}
		}
		if pieces > 32 || pieces < minPieces {
			continue
		}
		key := engine.BookKey(rec.FEN)
		if seen[key] {
			continue
		}
		pv, ok := rec.bestPV()
		if !ok {
			continue
		}
		g, err := game.ParseFEN(padFEN(rec.FEN))
		if err != nil {
			continue
		}
		// Replay the whole variation, writing an entry at every step. Each
		// position along it is one a deep search chose to enter, so each
		// is a position worth having a book move for.
		for _, mv := range pv {
			k := engine.BookKey(g.FEN())
			want, ok := game.MoveFromUCI(mv)
			if !ok {
				break
			}
			// Verified legal at build time, so a book miss at play time
			// means the position is absent rather than the entry wrong.
			var legal *game.Move
			for _, m := range g.AllLegalMoves(g.Turn) {
				if m.From == want.From && m.To == want.To {
					mm := m
					legal = &mm
					break
				}
			}
			if legal == nil {
				illegal++
				break
			}
			if !seen[k] {
				seen[k] = true
				if _, err := w.WriteString(padFEN(g.FEN()) + "|" + mv + "\n"); err != nil {
					return err
				}
				written++
			}
			g.Apply(want)
			if max > 0 && written >= max {
				break
			}
		}
		if written%20000 == 0 {
			fmt.Printf("  %d book moves from %d records, %s\n",
				written, read, time.Since(t0).Truncate(time.Second))
		}
	}
	fmt.Printf("wrote %d book moves to %s (from %d records, %d entries dropped as illegal, %s)\n",
		written, path, read, illegal, time.Since(t0).Truncate(time.Second))
	return nil
}

// ExtractTuning writes the dump in the format the Texel tuner reads:
// one JSON record per line with a FEN and a score.
//
// The conversion that matters is the sign. The dump stores scores from
// White's point of view; the tuner flips the score for a black-to-move
// position, which means it expects the UCI convention of scoring from the
// side to move. Writing White-relative scores into that file would negate
// the label on half the positions, which is the exact mistake that made
// the first import produce labels correlating 0.012 with material.
func ExtractTuning(r io.Reader, path string, max int, quietOnly bool, quietTol float64) error {
	f, err := os.Create(path)
	if err != nil {
		return err
	}
	defer f.Close()
	w := bufio.NewWriterSize(f, 1<<20)
	defer w.Flush()

	labeler := engine.Strong(1)
	sc := bufio.NewScanner(r)
	sc.Buffer(make([]byte, 1<<20), 1<<22)
	written, read := 0, 0
	t0 := time.Now()
	for sc.Scan() && (max <= 0 || written < max) {
		read++
		var rec evalLine
		if err := json.Unmarshal(sc.Bytes(), &rec); err != nil {
			continue
		}
		score, ok := rec.bestEval()
		if !ok {
			continue
		}
		g, err := game.ParseFEN(padFEN(rec.FEN))
		if err != nil {
			continue
		}
		if moves.IsInCheck(&g.Board, g.Turn) {
			continue
		}
		if quietOnly {
			static := engine.PlayerStaticEval(labeler, &g.Board)
			staticSTM := static
			if g.Turn == board.Black {
				staticSTM = -static
			}
			if math.Abs(engine.QuiescenceScore(labeler, g)-staticSTM) > quietTol {
				continue
			}
		}
		if score > 12 {
			score = 12
		} else if score < -12 {
			score = -12
		}
		// Into the tuner's convention: it negates for black to move.
		stm := score
		if g.Turn == board.Black {
			stm = -score
		}
		line, err := json.Marshal(map[string]any{"fen": padFEN(rec.FEN), "score": stm})
		if err != nil {
			continue
		}
		if _, err := w.Write(append(line, '\n')); err != nil {
			return err
		}
		written++
		if written%100000 == 0 {
			fmt.Printf("  %d tuning positions from %d records, %s\n",
				written, read, time.Since(t0).Truncate(time.Second))
		}
	}
	fmt.Printf("wrote %d tuning positions to %s (from %d records, %s)\n",
		written, path, read, time.Since(t0).Truncate(time.Second))
	return nil
}

// LoadOpenings reads a book written by ExtractOpenings.
func LoadOpenings(path string) ([]string, error) {
	f, err := os.Open(path)
	if err != nil {
		return nil, err
	}
	defer f.Close()
	var out []string
	sc := bufio.NewScanner(f)
	sc.Buffer(make([]byte, 1<<16), 1<<20)
	for sc.Scan() {
		if line := strings.TrimSpace(sc.Text()); line != "" {
			out = append(out, line)
		}
	}
	return out, sc.Err()
}

type importStats struct {
	lines, parsed, kept, noEval, badFEN, inCheck, noisy int64
}

// ImportLichess reads the JSONL dump from r and appends training samples
// to the pool.
//
// It is written to be killed and restarted: samples are appended in
// batches and the number of lines consumed is recorded next to the pool,
// so a second run resumes rather than re-paying for the work. That
// matters because the input is a 21 GB stream, and losing an hour of it
// to a laptop sleeping is the failure this design exists to prevent.
func ImportLichess(r io.Reader, poolPath string, maxKeep int, quietTol float64, filterQuiet bool, resume bool) error {
	progressPath := poolPath + ".progress"

	skip := int64(0)
	if resume {
		if data, err := os.ReadFile(progressPath); err == nil {
			if n, err := strconv.ParseInt(strings.TrimSpace(string(data)), 10, 64); err == nil {
				skip = n
			}
		}
	}
	if skip > 0 {
		fmt.Printf("resuming: skipping %d lines already imported\n", skip)
	}

	workers := runtime.NumCPU()
	lines := make(chan []byte, workers*64)
	out := make(chan []sample, workers)

	var st importStats
	var wg sync.WaitGroup
	for w := 0; w < workers; w++ {
		wg.Add(1)
		go func() {
			defer wg.Done()
			// Each worker keeps its own evaluator and transposition table:
			// the quiet filter runs a quiescence search per position, and
			// sharing one table across ten cores was measured contended
			// enough to dominate a profile once already.
			labeler := engine.Strong(1)
			batch := make([]sample, 0, 256)
			var rec evalLine
			for raw := range lines {
				rec = evalLine{}
				if err := json.Unmarshal(raw, &rec); err != nil {
					continue
				}
				atomic.AddInt64(&st.parsed, 1)
				score, ok := rec.bestEval()
				if !ok {
					atomic.AddInt64(&st.noEval, 1)
					continue
				}
				g, err := game.ParseFEN(padFEN(rec.FEN))
				if err != nil {
					atomic.AddInt64(&st.badFEN, 1)
					continue
				}
				if moves.IsInCheck(&g.Board, g.Turn) {
					atomic.AddInt64(&st.inCheck, 1)
					continue
				}
				static := engine.PlayerStaticEval(labeler, &g.Board)
				if filterQuiet {
					staticSTM := static
					if g.Turn == board.Black {
						staticSTM = -static
					}
					if math.Abs(engine.QuiescenceScore(labeler, g)-staticSTM) > quietTol {
						atomic.AddInt64(&st.noisy, 1)
						continue
					}
				}
				// The dump's scores are already from White's point of
				// view, so there is no flip here.
				//
				// This was got wrong first time by assuming the UCI
				// convention (score from the side to move), and it is
				// worth recording how the mistake was caught, because
				// nothing about the run looked broken. Flipping the
				// black-to-move half of the data leaves the labels almost
				// exactly uncorrelated with material: measured 0.012
				// against the hand-written evaluation, because half the
				// positions then correlate strongly positive and half
				// strongly negative. The network learned nothing at all,
				// 0.8% of held-out variance, while its loss still compared
				// favourably against the hand evaluation and read as
				// healthy.
				//
				// Checked against the file rather than reasoned about:
				// over 15,834 records whose material is lopsided by five
				// pawns or more, the sign of cp agrees with the side that
				// is up material 72.5% of the time as written, and 48.4%
				// of the time after a side-to-move flip, which is chance.
				if score > 12 {
					score = 12
				} else if score < -12 {
					score = -12
				}
				var own, opp []int32
				own = engine.AppendHalfKPFeatures(own, &g.Board, board.White)
				opp = engine.AppendHalfKPFeatures(opp, &g.Board, board.Black)
				batch = append(batch, sample{
					own: own, opp: opp, target: score, static: static,
					// Positions are grouped in blocks of 32 so that the
					// by-game validation split still separates neighbours.
					// The dump does not say which game a position came
					// from, and consecutive records can be one analysis.
					game: int32(atomic.LoadInt64(&st.parsed) / 32),
				})
				if len(batch) == cap(batch) {
					out <- batch
					batch = make([]sample, 0, 256)
				}
			}
			if len(batch) > 0 {
				out <- batch
			}
		}()
	}

	go func() { wg.Wait(); close(out) }()

	// Feed the workers.
	go func() {
		defer close(lines)
		sc := bufio.NewScanner(r)
		sc.Buffer(make([]byte, 1<<20), 1<<22) // records carry long PV lines
		for sc.Scan() {
			n := atomic.AddInt64(&st.lines, 1)
			if n <= skip {
				continue
			}
			lines <- append([]byte(nil), sc.Bytes()...)
		}
	}()

	t0 := time.Now()
	pending := make([]sample, 0, 8192)
	flush := func() error {
		if len(pending) == 0 {
			return nil
		}
		if err := appendPool(poolPath, pending); err != nil {
			return err
		}
		// The line count is written only after the samples are on disk, so
		// a crash between the two costs a re-read, never a silent gap.
		_ = os.WriteFile(progressPath,
			[]byte(strconv.FormatInt(atomic.LoadInt64(&st.lines), 10)), 0644)
		pending = pending[:0]
		return nil
	}

	lastReport := time.Now()
	for batch := range out {
		pending = append(pending, batch...)
		atomic.AddInt64(&st.kept, int64(len(batch)))
		if len(pending) >= 8192 {
			if err := flush(); err != nil {
				return err
			}
		}
		if time.Since(lastReport) > 10*time.Second {
			lastReport = time.Now()
			kept := atomic.LoadInt64(&st.kept)
			el := time.Since(t0).Seconds()
			fmt.Printf("%8d read  %8d kept  %6.0f kept/s  %s\n",
				atomic.LoadInt64(&st.lines), kept, float64(kept)/el,
				time.Since(t0).Truncate(time.Second))
		}
		if maxKeep > 0 && atomic.LoadInt64(&st.kept) >= int64(maxKeep) {
			break
		}
	}
	if err := flush(); err != nil {
		return err
	}

	fmt.Printf("\nimported %d positions from %d records in %s\n",
		st.kept, st.parsed, time.Since(t0).Truncate(time.Second))
	fmt.Printf("  rejected: %d no usable score (mate or empty), %d unparseable, %d in check, %d not quiet\n",
		st.noEval, st.badFEN, st.inCheck, st.noisy)
	return nil
}
